services:

  db:
    image: postgres
    restart: none
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: none
    ports:
      - 8081:8080

volumes:
  db: